import { SignalJSON, PerformanceStats, Tick } from '../types/market';

export class SignalTracker {
  private activeSignal: SignalJSON | null = null;
  private signalHistory: SignalJSON[] = [];
  private listeners: Set<(active: SignalJSON | null, history: SignalJSON[], stats: PerformanceStats) => void> = new Set();

  constructor() {
    if (typeof window !== 'undefined') {
      this.loadFromStorage();
    }
  }

  private loadFromStorage() {
    try {
      const savedHistory = localStorage.getItem('STEP_INDEX_SIGNAL_HISTORY');
      if (savedHistory) {
        this.signalHistory = JSON.parse(savedHistory);
      }
      const savedActive = localStorage.getItem('STEP_INDEX_ACTIVE_SIGNAL');
      if (savedActive) {
        this.activeSignal = JSON.parse(savedActive);
      }
    } catch (e) {
      console.error('Failed to load signal data from storage', e);
    }
  }

  private saveToStorage() {
    if (typeof window === 'undefined') return;
    try {
      localStorage.setItem('STEP_INDEX_SIGNAL_HISTORY', JSON.stringify(this.signalHistory));
      if (this.activeSignal) {
        localStorage.setItem('STEP_INDEX_ACTIVE_SIGNAL', JSON.stringify(this.activeSignal));
      } else {
        localStorage.removeItem('STEP_INDEX_ACTIVE_SIGNAL');
      }
    } catch (e) {
      console.error('Failed to save signal data to storage', e);
    }
  }

  public getActiveSignal(): SignalJSON | null {
    return this.activeSignal;
  }

  public getSignalHistory(): SignalJSON[] {
    return [...this.signalHistory];
  }

  public subscribe(listener: (active: SignalJSON | null, history: SignalJSON[], stats: PerformanceStats) => void): () => void {
    this.listeners.add(listener);
    listener(this.activeSignal, this.getSignalHistory(), this.calculatePerformance());
    return () => this.listeners.delete(listener);
  }

  private notify() {
    const stats = this.calculatePerformance();
    this.listeners.forEach((l) => l(this.activeSignal, this.getSignalHistory(), stats));
  }

  /**
   * Registers a new signal generated by the strategy engine.
   */
  public registerSignal(signal: SignalJSON) {
    // If we already have an active signal running for the same symbol, don't override
    if (this.activeSignal && this.activeSignal.result === 'RUNNING') {
      return;
    }

    // Set running state
    const runningSignal: SignalJSON = {
      ...signal,
      status: 'RUNNING',
      result: 'RUNNING',
    };

    this.activeSignal = runningSignal;
    this.saveToStorage();
    this.notify();
  }

  /**
   * Evaluates current active signal against live tick price.
   */
  public processTick(tick: Tick) {
    if (!this.activeSignal || this.activeSignal.result !== 'RUNNING') return;

    const s = this.activeSignal;
    const price = tick.quote;
    const now = Date.now();
    const duration = Math.floor((now - s.timestamp) / 1000);
    s.duration_seconds = duration;

    const isBuy = s.signal === 'BUY';

    // BUY TRADE CHECKS
    if (isBuy) {
      // Check SL hit
      if (price <= s.stop_loss) {
        s.result = 'SL_HIT';
        s.status = 'SL_HIT';
        s.exit_price = price;
        s.exit_timestamp = now;
        s.r_multiple = s.management.after_tp1 === 'PROTECTED_BE' ? 0.0 : -1.0;
        this.archiveActiveSignal();
        return;
      }

      // Check TP1 hit
      if (price >= s.take_profit_1 && s.management.tp1_action === 'PARTIAL_PROFIT') {
        s.management.tp1_action = 'TP1_SECURED';
        s.management.after_tp1 = 'PROTECTED_BE';
        // Move Stop Loss to Break Even (entry price)
        s.stop_loss = s.entry;
        this.saveToStorage();
        this.notify();
      }

      // Check TP2 hit (Full Target)
      if (price >= s.take_profit_2) {
        s.result = 'TP2_HIT';
        s.status = 'TP2_HIT';
        s.exit_price = price;
        s.exit_timestamp = now;
        s.r_multiple = 2.8;
        this.archiveActiveSignal();
        return;
      }
    } else {
      // SELL TRADE CHECKS
      // Check SL hit
      if (price >= s.stop_loss) {
        s.result = 'SL_HIT';
        s.status = 'SL_HIT';
        s.exit_price = price;
        s.exit_timestamp = now;
        s.r_multiple = s.management.after_tp1 === 'PROTECTED_BE' ? 0.0 : -1.0;
        this.archiveActiveSignal();
        return;
      }

      // Check TP1 hit
      if (price <= s.take_profit_1 && s.management.tp1_action === 'PARTIAL_PROFIT') {
        s.management.tp1_action = 'TP1_SECURED';
        s.management.after_tp1 = 'PROTECTED_BE';
        // Move Stop Loss to Break Even
        s.stop_loss = s.entry;
        this.saveToStorage();
        this.notify();
      }

      // Check TP2 hit
      if (price <= s.take_profit_2) {
        s.result = 'TP2_HIT';
        s.status = 'TP2_HIT';
        s.exit_price = price;
        s.exit_timestamp = now;
        s.r_multiple = 2.8;
        this.archiveActiveSignal();
        return;
      }
    }

    this.notify();
  }

  private archiveActiveSignal() {
    if (!this.activeSignal) return;
    this.signalHistory.unshift(this.activeSignal);
    if (this.signalHistory.length > 100) {
      this.signalHistory.pop();
    }
    this.activeSignal = null;
    this.saveToStorage();
    this.notify();
  }

  public clearHistory() {
    this.signalHistory = [];
    this.activeSignal = null;
    this.saveToStorage();
    this.notify();
  }

  /**
   * Computes authentic performance metrics based strictly on recorded signals.
   */
  public calculatePerformance(): PerformanceStats {
    const closed = this.signalHistory.filter((s) => s.result && s.result !== 'RUNNING');
    const total = closed.length;

    if (total === 0) {
      return {
        totalSignals: 0,
        winningSignals: 0,
        losingSignals: 0,
        winRate: 0,
        averageR: 0,
        profitFactor: 0,
        maxDrawdown: 0,
        tp1HitRate: 0,
        tp2HitRate: 0,
      };
    }

    let wins = 0;
    let losses = 0;
    let tp1Hits = 0;
    let tp2Hits = 0;
    let sumR = 0;
    let grossGains = 0;
    let grossLosses = 0;

    let peakR = 0;
    let currentR = 0;
    let maxDd = 0;

    closed.forEach((s) => {
      const r = s.r_multiple ?? (s.result === 'TP2_HIT' ? 2.8 : s.result === 'TP1_HIT' ? 1.0 : -1.0);
      sumR += r;
      currentR += r;
      if (currentR > peakR) peakR = currentR;
      const dd = peakR - currentR;
      if (dd > maxDd) maxDd = dd;

      if (r > 0) {
        wins++;
        grossGains += r;
      } else if (r < 0) {
        losses++;
        grossLosses += Math.abs(r);
      }

      if (s.result === 'TP1_HIT' || s.result === 'TP2_HIT' || s.management.tp1_action === 'TP1_SECURED') {
        tp1Hits++;
      }
      if (s.result === 'TP2_HIT') {
        tp2Hits++;
      }
    });

    const winRate = Number(((wins / total) * 100).toFixed(1));
    const averageR = Number((sumR / total).toFixed(2));
    const profitFactor = grossLosses > 0 ? Number((grossGains / grossLosses).toFixed(2)) : grossGains > 0 ? 9.99 : 0;
    const tp1HitRate = Number(((tp1Hits / total) * 100).toFixed(1));
    const tp2HitRate = Number(((tp2Hits / total) * 100).toFixed(1));

    return {
      totalSignals: total,
      winningSignals: wins,
      losingSignals: losses,
      winRate,
      averageR,
      profitFactor,
      maxDrawdown: Number(maxDd.toFixed(2)),
      tp1HitRate,
      tp2HitRate,
    };
  }
}

export const signalTracker = new SignalTracker();
